# instruct GitHub dependabot to scan github actions and python code for dependency updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    # dependabot automatically checks .github/workflows/ and .github/actions/
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/requirements/"
    schedule:
      interval: "weekly"
